name: temir_yol_task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # for network
  dio: ^5.3.3
  # for state management
  flutter_bloc: ^8.1.3
  # for DI
  get_it: ^7.6.4

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Name launcher
  rename_app: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
